language: python

python:
 - "2.7"

services:
 - couchdb
 - redis-server
 - elasticsearch

install:
 - pip install -r requirements.txt --allow-external argparse

before_script:
  - psql -c 'create database mygpo_test;' -U postgres

script:
  python manage.py test

env:
 - DATABASE_URL="postgres://postgres@localhost/mygpo_test"
